In [1]:
a=10
b=12
print(a+b)

22


In [2]:
a=10
b=12
c=15
max=0
if a > b and a > c:
    print ("a is greatest") 
  
elif b >c and b > a:
    print("b is greatest")
else :
  print ("c is greatest")
 

c is greatest


In [3]:
# greatest in list
lis=[9,5,6]
max=0
for i in lis:
  if i>max:
    max=i
print(max)

9


In [5]:
# TO FIND REVERSE
a=[3,5,7,9]
b=[]
for i in range(len(a)-1,-1,-1):
  b.append(a[i])
print(b)

[9, 7, 5, 3]


In [6]:
# generate fibonacci series

a=0
b=1
print(a)
print(b)
n=7
for i in range(1,n):
  sum = a+b
  a=b
  b=sum
  print(sum)

0
1
1
2
3
5
8
13


In [7]:
# fibonacci series by function

def fibonacci(n):
  a=0
  b=1
  print(a)
  print(b)
  for i in range (1,n):
    c=a+b
    a=b
    b=c
    print(c)

In [8]:
# Numpy
import numpy as np
arr = np.array([[1,2,3],[4,2,5]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


In [9]:
import numpy as np
x = np.array ([1,2,3])
y = np.array ([5,6,7])

In [10]:
x

array([1, 2, 3])

# NUMPY

In [23]:
import random
import numpy as np
a = np.random.randint(low=1,high=3,size=(3,3)) # generating a matrix between 1-3 with 3 rows and 3 columns
print(a)

[[2 1 1]
 [2 1 2]
 [1 2 1]]


In [22]:
b = np.random.randint (low=2,high=4,size=(3,3)) # generating a matrix between 2-4 with 3 rows and 3 columns
print(b)

[[2 3 2]
 [2 3 3]
 [2 2 2]]


In [28]:
dot  = np.dot(a,b) # dot product of two vectors
print(c)

[[ 8 11  9]
 [10 13 11]
 [ 8 11 10]]


In [30]:
cross= np.cross(a,b) # cross product of two vectors
print(cross)

[[-1 -2  4]
 [-3 -2  4]
 [ 2  0 -2]]


In [31]:
add = np.add(a,b) # addition of two vectors
print(add)

[[4 4 3]
 [4 4 5]
 [3 4 3]]


In [35]:
x= np.random.randn(3,3) # generates random number 
print(x)

[[-0.16448678 -0.71518405 -0.05974179]
 [ 0.12577824 -0.44613247 -0.02784177]
 [ 0.62725958  0.43716961  0.77670104]]


In [36]:
# dot, cross, add of vectors

import random
a= np.random.randint(1,9, (2,2))
b= np.random.randint(1,9, (2,2))
abdot= np.dot(a, b)
abcross= np.cross(a, b)
abadd= np.add(a,b)
print(a)
print(b)
print("dot prod\n", abdot)
print("cross product\n", abcross)
print("add\n", abadd)

[[5 3]
 [6 8]]
[[4 4]
 [8 6]]
dot prod
 [[44 38]
 [88 72]]
cross product
 [  8 -28]
add
 [[ 9  7]
 [14 14]]
